### ISSUE TITLE
KeyError: Key not found: sec-websocket-accept in linux

### ISSUE THREAD

**Issue by uzaif313** [palkan/acli#3]
KeyError: Key not found: sec-websocket-accept in ubuntu

i have invoke cli with below command 

`sudo ./acli-linux-x86_64 -u http://localhost:3000/cabel -c waiting_room_channel`

**Comment by palkan** [comment]
That means that the server response doesn't contain the `sec-websocket-accept` key.

Isn't there a typo in you url? `cabel` -> `cable`

**Comment by uzaif313** [comment]
@palkan Thanks
